name: Build & Push Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BACKEND: ${{ github.repository }}/backend
  IMAGE_NAME_FRONTEND: ${{ github.repository }}/frontend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # needed to push to GHCR
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend
        run: |
          docker build -t ghcr.io/${{ env.IMAGE_NAME_BACKEND }}:latest ./backend
          docker push ghcr.io/${{ env.IMAGE_NAME_BACKEND }}:latest

      - name: Build frontend
        run: |
          docker build -t ghcr.io/${{ env.IMAGE_NAME_FRONTEND }}:latest ./frontend
          docker push ghcr.io/${{ env.IMAGE_NAME_FRONTEND }}:latest
