name: Nightly Jobs

on:
  schedule:
    - cron: "0 2 * * *"   # 02:00 UTC daily
  workflow_dispatch:

jobs:
  scrape_and_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r backend/requirements.txt

      - name: Run deal sourcing scraper
        env:
          SCRAPER_USER_AGENT: ${{ secrets.SCRAPER_USER_AGENT }}
        run: python automation/pipelines/deal_sourcing.py

      - name: Build quarterly report PDF (demo)
        run: python automation/reports/quarterly_report.py

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarterly-report
          path: quarterly_report_demo.pdf
