name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create zip
        run: |
          zip -r autoinfra-capital-${{ github.ref_name }}.zip . -x "*.git*"
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: autoinfra-capital-${{ github.ref_name }}.zip
